# Generated by Django 5.0.2 on 2024-02-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='business',
            field=models.CharField(default='Business Name', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.CharField(default='Customer Name', max_length=100),
        ),
    ]
