# Generated by Django 5.0.2 on 2024-03-01 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0002_invoice_business_invoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
